{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.devmre",
    "module": "navigation",
    "version": "1.3.0-alpha15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.6"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.6"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.8"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation3",
          "module": "navigation3-ui",
          "version": {
            "requires": "1.0.0-alpha06"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-metadata-1.3.0-alpha15.jar",
          "url": "navigation-1.3.0-alpha15.jar",
          "size": 13710,
          "sha512": "50a8aae028962700a2063a89364592657b29116fbd70e73eb1176f6c8b996fb0b45964c1d047737f534c4f6ab6e5bf641ef3088562ca0f1b48864f026d405946",
          "sha256": "a3a802a3d978b71e10b6bf55a325596db30d50d419cc79f7210a2640fd585d3c",
          "sha1": "0326a72b4d23a327d3b57cc90aa8ead26c492cbc",
          "md5": "f9c47a665b6330afd7d3f17b179aad52"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "navigation-kotlin-1.3.0-alpha15-sources.jar",
          "url": "navigation-1.3.0-alpha15-sources.jar",
          "size": 18406,
          "sha512": "65344c2d6d73707d8208c9bc9ea9b1fecc0a3c00b8d7de553a1694a2f6a624293a9b567daf924a89944553d83f767869e021196f10d891ad43348efd2cf0dbf9",
          "sha256": "7772c1e52b7f9b01f9cdae27f45d05ff548580dbe8d5d129d7569f3dcceefe8d",
          "sha1": "86d2ebb2fbd0eae41678a85a8fb01547d6d97d28",
          "md5": "0dd90a6679e49843c62bb10d8b430766"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../navigation-android/1.3.0-alpha15/navigation-android-1.3.0-alpha15.module",
        "group": "com.github.devmre",
        "module": "navigation-android",
        "version": "1.3.0-alpha15"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../navigation-android/1.3.0-alpha15/navigation-android-1.3.0-alpha15.module",
        "group": "com.github.devmre",
        "module": "navigation-android",
        "version": "1.3.0-alpha15"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../navigation-android/1.3.0-alpha15/navigation-android-1.3.0-alpha15.module",
        "group": "com.github.devmre",
        "module": "navigation-android",
        "version": "1.3.0-alpha15"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../navigation-desktop/1.3.0-alpha15/navigation-desktop-1.3.0-alpha15.module",
        "group": "com.github.devmre",
        "module": "navigation-desktop",
        "version": "1.3.0-alpha15"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../navigation-desktop/1.3.0-alpha15/navigation-desktop-1.3.0-alpha15.module",
        "group": "com.github.devmre",
        "module": "navigation-desktop",
        "version": "1.3.0-alpha15"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../navigation-desktop/1.3.0-alpha15/navigation-desktop-1.3.0-alpha15.module",
        "group": "com.github.devmre",
        "module": "navigation-desktop",
        "version": "1.3.0-alpha15"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation-iosarm64/1.3.0-alpha15/navigation-iosarm64-1.3.0-alpha15.module",
        "group": "com.github.devmre",
        "module": "navigation-iosarm64",
        "version": "1.3.0-alpha15"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation-iosarm64/1.3.0-alpha15/navigation-iosarm64-1.3.0-alpha15.module",
        "group": "com.github.devmre",
        "module": "navigation-iosarm64",
        "version": "1.3.0-alpha15"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation-iosarm64/1.3.0-alpha15/navigation-iosarm64-1.3.0-alpha15.module",
        "group": "com.github.devmre",
        "module": "navigation-iosarm64",
        "version": "1.3.0-alpha15"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation-iosarm64/1.3.0-alpha15/navigation-iosarm64-1.3.0-alpha15.module",
        "group": "com.github.devmre",
        "module": "navigation-iosarm64",
        "version": "1.3.0-alpha15"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation-iossimulatorarm64/1.3.0-alpha15/navigation-iossimulatorarm64-1.3.0-alpha15.module",
        "group": "com.github.devmre",
        "module": "navigation-iossimulatorarm64",
        "version": "1.3.0-alpha15"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation-iossimulatorarm64/1.3.0-alpha15/navigation-iossimulatorarm64-1.3.0-alpha15.module",
        "group": "com.github.devmre",
        "module": "navigation-iossimulatorarm64",
        "version": "1.3.0-alpha15"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation-iossimulatorarm64/1.3.0-alpha15/navigation-iossimulatorarm64-1.3.0-alpha15.module",
        "group": "com.github.devmre",
        "module": "navigation-iossimulatorarm64",
        "version": "1.3.0-alpha15"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../navigation-iossimulatorarm64/1.3.0-alpha15/navigation-iossimulatorarm64-1.3.0-alpha15.module",
        "group": "com.github.devmre",
        "module": "navigation-iossimulatorarm64",
        "version": "1.3.0-alpha15"
      }
    }
  ]
}
