{
  "formatVersion": "1.1",
  "component": {
    "url": "../../navigation/1.3.0-alpha15/navigation-1.3.0-alpha15.module",
    "group": "com.github.devmre",
    "module": "navigation",
    "version": "1.3.0-alpha15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "navigation-desktop-1.3.0-alpha15.jar",
          "url": "navigation-desktop-1.3.0-alpha15.jar",
          "size": 89201,
          "sha512": "2efcc407443b2b3341517075a24002cac578a2974ed2e8c1a33f4692c6ca86b859fcd91bd118cd083b883e2e849309a5e1a275efcb93b61c7f96c6817e2273dd",
          "sha256": "e8f6369163cee075ac11bfb81cd8c929befcab02c3e6ecc27c1a60dddb8c31da",
          "sha1": "67be0214af3caaee143dda5e53e412ecb7875236",
          "md5": "ace6446e103d99fcd9ef4e2b444dedeb"
        }
      ]
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.10"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.6"
          }
        },
        {
          "group": "org.jetbrains.androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.9.6"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-core",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-compose",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "kermit",
          "version": {
            "requires": "2.0.8"
          }
        },
        {
          "group": "org.jetbrains.androidx.navigation3",
          "module": "navigation3-ui",
          "version": {
            "requires": "1.0.0-alpha06"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-desktop-1.3.0-alpha15.jar",
          "url": "navigation-desktop-1.3.0-alpha15.jar",
          "size": 89201,
          "sha512": "2efcc407443b2b3341517075a24002cac578a2974ed2e8c1a33f4692c6ca86b859fcd91bd118cd083b883e2e849309a5e1a275efcb93b61c7f96c6817e2273dd",
          "sha256": "e8f6369163cee075ac11bfb81cd8c929befcab02c3e6ecc27c1a60dddb8c31da",
          "sha1": "67be0214af3caaee143dda5e53e412ecb7875236",
          "md5": "ace6446e103d99fcd9ef4e2b444dedeb"
        }
      ]
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "navigation-desktop-1.3.0-alpha15-sources.jar",
          "url": "navigation-desktop-1.3.0-alpha15-sources.jar",
          "size": 18406,
          "sha512": "65344c2d6d73707d8208c9bc9ea9b1fecc0a3c00b8d7de553a1694a2f6a624293a9b567daf924a89944553d83f767869e021196f10d891ad43348efd2cf0dbf9",
          "sha256": "7772c1e52b7f9b01f9cdae27f45d05ff548580dbe8d5d129d7569f3dcceefe8d",
          "sha1": "86d2ebb2fbd0eae41678a85a8fb01547d6d97d28",
          "md5": "0dd90a6679e49843c62bb10d8b430766"
        }
      ]
    }
  ]
}
